CREATE TYPE crawl_status AS ENUM ('RUNNING', 'SUCCESS', 'FAILED');

CREATE TABLE "public"."crawl_jobs"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "source_name"   character varying REFERENCES "public"."sources" ("name"),
    "started_at"    TIMESTAMP    NOT NULL DEFAULT NOW(),
    "finished_at"   TIMESTAMP,
    "status"        crawl_status NOT NULL,
    "books_found"   int                   DEFAULT 0,
    "error_message" TEXT,
    PRIMARY KEY ("started_at")
);
