CREATE TYPE crawl_status AS ENUM ('RUNNING', 'SUCCESS', 'FAILED');

CREATE TABLE crawl_jobs
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "source_name"   character varying REFERENCES sources ("name") ON DELETE CASCADE,
    "started_at"    TIMESTAMP    NOT NULL DEFAULT NOW(),
    "finished_at"   TIMESTAMP,
    "status"        crawl_status NOT NULL,
    "books_found"   int                   DEFAULT 0,
    "error_message" TEXT,
    PRIMARY KEY ("id")
);

CREATE INDEX idx_crawl_jobs_status_source_name ON crawl_jobs ("status", "source_name");
