CREATE TABLE purgatory
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "invalid_isbn"  character varying NOT NULL,
    "title"         character varying NOT NULL,
    "authors"       jsonb             NOT NULL,
    "url"           character varying NOT NULL,
    "source_name"   character varying NOT NULL REFERENCES sources ("name") ON DELETE CASCADE,
    "resolved_isbn" character varying REFERENCES books ("isbn") ON DELETE SET NULL,
    "created_at"    TIMESTAMP         NOT NULL DEFAULT NOW(),
    "deleted"       boolean           NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE INDEX idx_purgatory_pending_queue ON purgatory ("resolved_isbn")
    WHERE "resolved_isbn" IS NULL AND "deleted" = false;
CREATE INDEX idx_purgatory_resolved_isbn ON purgatory ("resolved_isbn");
CREATE INDEX idx_purgatory_title_trgm ON purgatory USING gist ("title" gist_trgm_ops);

ALTER TABLE purgatory
    ADD CONSTRAINT purgatory_invalid_isbn_source_name_key UNIQUE ("invalid_isbn", "source_name");
