CREATE TABLE "public"."purgatory"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY,
    "invalid_isbn"  character varying NOT NULL,
    "title"         character varying NOT NULL,
    "authors"       jsonb             NOT NULL,
    "url"           character varying NOT NULL,
    "source_name"   character varying NOT NULL REFERENCES "public"."sources" ("name"),
    "resolved_isbn" character varying REFERENCES "public"."books" ("isbn"),
    "created_at"    TIMESTAMP         NOT NULL DEFAULT NOW(),
    "deleted"       boolean           NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE INDEX purgatory_invalid_isbn_idx ON "public"."purgatory" ("invalid_isbn");
CREATE INDEX purgatory_resolved_isbn_idx ON "public"."purgatory" ("resolved_isbn");

INSERT INTO "public"."purgatory" ("invalid_isbn", "title", "authors", "url", "source_name")
SELECT isbn, title, authors, url, source_name
FROM "public"."books"
WHERE length(isbn) NOT IN (10, 13);

DELETE
FROM "public"."books"
WHERE length(isbn) NOT IN (10, 13);
